// Writes lib/utils/icon_catalogue.g.dart: the icons the icon picker offers,
// with the categories and search words Lucide publishes for them.
//
//   dart run tool/generate_icon_catalogue.dart
//
// Run it after bumping lucide_icons_flutter, and commit the result. It is not
// part of the build: the app and CI never go to the network for icons, and
// the glyphs themselves are already in the package's font.
//
// The metadata is read at the Lucide release the installed package was built
// from (its changelog names it), so names, tags and glyphs always agree. A
// glyph the package does not have is left out; one Lucide renames turns into
// a compile error in the generated file until this is run again.

import 'dart:async';
import 'dart:convert';
import 'dart:io';

/// Lucide's categories the picker offers, in the order it lists them. These
/// fit places and ways of travelling; the rest (development, text, arrows,
/// gaming, finance and so on) would bury them.
const List<String> _categories = [
  'transportation',
  'travel',
  'maps',
  'navigation',
  'buildings',
  'home',
  'food-beverage',
  'shopping',
  'sports',
  'nature',
  'animals',
  'weather',
  'seasons',
  'people',
  'emoji',
  'medical',
];

/// Icons worth offering whose own categories are all outside [_categories],
/// and where to list them instead.
const Map<String, String> _alsoInclude = {
  'key-round': 'transportation',
  'key': 'transportation',
  'shapes': 'travel',
  'briefcase': 'buildings',
  'heart': 'emoji',
  'star': 'emoji',
  'music': 'home',
};

/// Search words Lucide's tags lack but riders will type.
const Map<String, List<String>> _extraWords = {
  'car-taxi-front': ['taxi', 'cab'],
  'truck': ['lorry', 'hgv'],
  'scooter': ['e-scooter', 'kick scooter'],
  'bike': ['bicycle', 'cycle'],
  'house': ['home'],
  'key-round': ['sharing', 'rent', 'borrow'],
  'key': ['sharing', 'rent', 'borrow'],
  'map-pin': ['place', 'location'],
  'train-front': ['rail'],
  'train-front-tunnel': ['metro', 'subway', 'underground'],
  'tram-front': ['light rail'],
  'ship': ['ferry', 'boat'],
  'footprints': ['walk', 'foot'],
};

const String _package = 'lucide_icons_flutter';
const String _output = 'lib/utils/icon_catalogue.g.dart';
const int _parallelDownloads = 16;
const int _attempts = 3;

Future<void> main(List<String> args) async {
  final root = await _packageRoot();
  final packageVersion = _yamlValue(
    File('${root.path}/pubspec.yaml').readAsStringSync(),
    'version',
  );
  final lucideVersion = args.isNotEmpty
      ? args.first
      : _lucideVersionFor(
          packageVersion,
          File('${root.path}/CHANGELOG.md').readAsStringSync(),
        );
  stdout.writeln('$_package $packageVersion → Lucide $lucideVersion');

  final names =
      (jsonDecode(File('${root.path}/assets/info.json').readAsStringSync())
              as Map<String, dynamic>)
          .keys
          .toList()
        ..sort();
  final constants = RegExp(r'static const IconData (\w+) =')
      .allMatches(File('${root.path}/lib/lucide_icons.dart').readAsStringSync())
      .map((m) => m.group(1)!)
      .toSet();

  final client = HttpClient();
  final metadata = <String, Map<String, dynamic>>{};
  final queue = [...names];
  Future<void> worker() async {
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      metadata[name] = await _fetchMetadata(client, lucideVersion, name);
    }
  }

  await Future.wait([for (var i = 0; i < _parallelDownloads; i++) worker()]);
  client.close();

  final entries = <String>[];
  for (final name in names) {
    final constant = _camelCase(name);
    if (!constants.contains(constant)) continue;
    final meta = metadata[name]!;
    final categories = [
      for (final category in (meta['categories'] as List).cast<String>())
        if (_categories.contains(category)) category,
    ];
    final listedInstead = _alsoInclude[name];
    if (categories.isEmpty && listedInstead != null) {
      categories.add(listedInstead);
    }
    if (categories.isEmpty) continue;
    categories.sort(
      (a, b) => _categories.indexOf(a).compareTo(_categories.indexOf(b)),
    );
    final words = {
      ...(meta['tags'] as List).cast<String>(),
      ...?_extraWords[name],
    };
    entries.add(
      "  CatalogueIcon('$name', LucideIcons.$constant, "
      '[${categories.map((c) => 'IconCategory.${_camelCase(c)}').join(', ')}], '
      '[${words.map(_quoted).join(', ')}]),',
    );
  }

  File(_output).writeAsStringSync('''
// GENERATED by tool/generate_icon_catalogue.dart. Do not edit by hand.
//
// Lucide $lucideVersion, as bundled by $_package $packageVersion.
// Icons and metadata: ISC licence, https://lucide.dev.

part of 'icon_catalogue.dart';

const List<CatalogueIcon> _generatedIcons = [
${entries.join('\n')}
];
''');
  final format = await Process.run('dart', ['format', _output]);
  if (format.exitCode != 0) stderr.write(format.stderr);
  stdout.writeln('Wrote ${entries.length} icons to $_output');
}

Future<Directory> _packageRoot() async {
  final config =
      jsonDecode(File('.dart_tool/package_config.json').readAsStringSync())
          as Map<String, dynamic>;
  final package = (config['packages'] as List)
      .cast<Map<String, dynamic>>()
      .firstWhere((p) => p['name'] == _package);
  final uri = Uri.parse(package['rootUri'] as String);
  // Relative roots are relative to the config file's own folder.
  return Directory.fromUri(
    uri.isAbsolute ? uri : Directory('.dart_tool').absolute.uri.resolveUri(uri),
  );
}

/// The Lucide release a package version was built from: its changelog lists
/// it on the line under the version's heading.
String _lucideVersionFor(String packageVersion, String changelog) {
  final lines = changelog.split('\n');
  final heading = lines.indexWhere((l) => l.trim() == '## $packageVersion');
  if (heading >= 0) {
    for (final line in lines.skip(heading + 1)) {
      final text = line.trim();
      if (text.isEmpty) continue;
      if (RegExp(r'^\d+\.\d+\.\d+$').hasMatch(text)) return text;
      break;
    }
  }
  stderr.writeln(
    'No Lucide version under "## $packageVersion" in the changelog; '
    'pass it as the first argument.',
  );
  exit(64);
}

Future<Map<String, dynamic>> _fetchMetadata(
  HttpClient client,
  String version,
  String name,
) async {
  final url = Uri.parse(
    'https://raw.githubusercontent.com/lucide-icons/lucide/$version/icons/$name.json',
  );
  for (var attempt = 1; ; attempt++) {
    try {
      final request = await client.getUrl(url);
      final response = await request.close();
      final body = await response.transform(utf8.decoder).join();
      if (response.statusCode == HttpStatus.ok) {
        return jsonDecode(body) as Map<String, dynamic>;
      }
      // No metadata file: offer it nowhere rather than fail the run.
      if (response.statusCode == HttpStatus.notFound) {
        return const {'categories': [], 'tags': []};
      }
      throw HttpException('HTTP ${response.statusCode}', uri: url);
    } on IOException {
      if (attempt == _attempts) rethrow;
    }
  }
}

String _camelCase(String name) {
  final parts = name.split('-');
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

String _quoted(String text) {
  final escaped = text
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
  return "'$escaped'";
}

String _yamlValue(String yaml, String key) => RegExp(
  '^$key:\\s*(.+)\$',
  multiLine: true,
).firstMatch(yaml)!.group(1)!.trim();
