name: "Build"

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
jobs:  
  build:      
    name: Build 
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '25'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.1'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
        
      - name: Build APK arm
        run: flutter build apk --release --split-per-abi --target-platform android-arm --split-debug-info=build/symbols --dart-define=CONTACT_EMAIL="$CONTACT_EMAIL"
        env:
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}

      - name: Build APK arm64
        run: flutter build apk --release --split-per-abi --target-platform android-arm64 --split-debug-info=build/symbols --dart-define=CONTACT_EMAIL="$CONTACT_EMAIL"
        env:
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}

      - name: Build appBundle
        run: flutter build appbundle --dart-define=CONTACT_EMAIL="$CONTACT_EMAIL"
        env:
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}

      - name: Validate Fastlane Supply Metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2.1.0
